// <auto-generated />
using LMS.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace LMS.Data.Migrations.PostgresMigrations
{
    [DbContext(typeof(AnalyticsDbContext))]
    [Migration("20250830220304_InitialAnalyticsSchema")]
    partial class InitialAnalyticsSchema
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("LMS.Models.postgress.DimCourse", b =>
                {
                    b.Property<int>("CourseId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("CourseId"));

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Difficulty")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("CourseId");

                    b.ToTable("dim_course", (string)null);

                    b.HasData(
                        new
                        {
                            CourseId = 1,
                            Category = "Programming",
                            Difficulty = "Beginner",
                            Title = "C# Basics"
                        },
                        new
                        {
                            CourseId = 2,
                            Category = "Analytics",
                            Difficulty = "Intermediate",
                            Title = "Data Science"
                        });
                });

            modelBuilder.Entity("LMS.Models.postgress.DimUser", b =>
                {
                    b.Property<int>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("UserId"));

                    b.Property<string>("Department")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("UserId");

                    b.ToTable("dim_user", (string)null);

                    b.HasData(
                        new
                        {
                            UserId = 1,
                            Department = "CS",
                            Name = "Alice",
                            Role = "Student"
                        },
                        new
                        {
                            UserId = 2,
                            Department = "Math",
                            Name = "Bob",
                            Role = "Student"
                        },
                        new
                        {
                            UserId = 3,
                            Department = "CS",
                            Name = "Dr. Smith",
                            Role = "Instructor"
                        });
                });

            modelBuilder.Entity("LMS.Models.postgress.FactCourseProgress", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.Property<int>("CourseId")
                        .HasColumnType("integer");

                    b.Property<int>("DateId")
                        .HasColumnType("integer");

                    b.Property<double>("CompletionPercent")
                        .HasColumnType("double precision");

                    b.Property<string>("ProgressStatus")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("TimeSpentMinutes")
                        .HasColumnType("integer");

                    b.HasKey("UserId", "CourseId", "DateId");

                    b.HasIndex("CourseId");

                    b.ToTable("fact_course_progress", (string)null);

                    b.HasData(
                        new
                        {
                            UserId = 1,
                            CourseId = 1,
                            DateId = 1,
                            CompletionPercent = 40.0,
                            ProgressStatus = "In Progress",
                            TimeSpentMinutes = 120
                        },
                        new
                        {
                            UserId = 2,
                            CourseId = 2,
                            DateId = 1,
                            CompletionPercent = 70.0,
                            ProgressStatus = "In Progress",
                            TimeSpentMinutes = 200
                        });
                });

            modelBuilder.Entity("LMS.Models.postgress.FactEngagement", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.Property<int>("CourseId")
                        .HasColumnType("integer");

                    b.Property<int>("ContentId")
                        .HasColumnType("integer");

                    b.Property<int>("DateId")
                        .HasColumnType("integer");

                    b.Property<int>("Clicks")
                        .HasColumnType("integer");

                    b.Property<int>("QuizAttempts")
                        .HasColumnType("integer");

                    b.Property<int>("Views")
                        .HasColumnType("integer");

                    b.HasKey("UserId", "CourseId", "ContentId", "DateId");

                    b.HasIndex("CourseId");

                    b.ToTable("fact_engagement", (string)null);

                    b.HasData(
                        new
                        {
                            UserId = 1,
                            CourseId = 1,
                            ContentId = 101,
                            DateId = 1,
                            Clicks = 10,
                            QuizAttempts = 1,
                            Views = 5
                        },
                        new
                        {
                            UserId = 2,
                            CourseId = 2,
                            ContentId = 202,
                            DateId = 1,
                            Clicks = 12,
                            QuizAttempts = 2,
                            Views = 8
                        });
                });

            modelBuilder.Entity("LMS.Models.postgress.FactCourseProgress", b =>
                {
                    b.HasOne("LMS.Models.postgress.DimCourse", "Course")
                        .WithMany("CourseProgressRecords")
                        .HasForeignKey("CourseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("LMS.Models.postgress.DimUser", "User")
                        .WithMany("CourseProgressRecords")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Course");

                    b.Navigation("User");
                });

            modelBuilder.Entity("LMS.Models.postgress.FactEngagement", b =>
                {
                    b.HasOne("LMS.Models.postgress.DimCourse", "Course")
                        .WithMany("EngagementRecords")
                        .HasForeignKey("CourseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("LMS.Models.postgress.DimUser", "User")
                        .WithMany("EngagementRecords")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Course");

                    b.Navigation("User");
                });

            modelBuilder.Entity("LMS.Models.postgress.DimCourse", b =>
                {
                    b.Navigation("CourseProgressRecords");

                    b.Navigation("EngagementRecords");
                });

            modelBuilder.Entity("LMS.Models.postgress.DimUser", b =>
                {
                    b.Navigation("CourseProgressRecords");

                    b.Navigation("EngagementRecords");
                });
#pragma warning restore 612, 618
        }
    }
}
